genres = {
    "anime": ['anime', 'anime score', 'j-pop', 'j-poprock', 'j-rock', 'japanese emo', 'japanese pop punk', 'otacore'],
    "blues": ['blues', 'blues rock', 'electric blues', 'modern blues', 'texas blues'],
    "classical": ['baroque', 'classical', 'early music', 'german baroque', 'early romantic era', 'polish classical', 'classical era', 'german romanticism'],
    "disco": ['disco', 'motown', 'post-disco', 'quiet storm'],
    "eletronic": ['deep tech house', 'disco house', 'edm', 'house', 'progressive house', 'tropical house', 'belgian edm', 'drum and bass', 'uk dnb', 'big beat', 'downtempo', 'electronica', 'trip hop', 'dance', 'alternative dance', 'electronica', 'electropop', 'neo-synthpop', 'new rave'],
    "folk": ['folk-pop', 'neo mellow'],
    "forro": ['forro', ],
    "funk": ['funk'],
    "gospel": ['gospel'],
    "hipHop": ['hip hop', 'hip-hop'],
    "indie": ['indie'],
    "jazz": ['jazz'],
    "kPop": ['k-pop', 'k pop'],
    "metal": ['metal', 'heavy metal'],
    "mpb": ['mpb', 'piada', 'baiao'],
    "pop": ['pop', 'pop rock'],
    "punk": ['punk', 'punk rock', 'punk-rock', 'brazilian hardcore', 'hardcore'],
    "reggae": ['reggae'],
    "rock": ['album rock', 'art rock', 'classic rock', 'folk rock', 'hard rock', 'psychedelic rock', 'rock', 'roots rock'],
    "salsa": ['salsa'],
    "samba": ['samba'],
    "soul": ['soul', 'southern soul', 'urban contemporary', 'chicago soul', 'classic soul', 'r&b'],
    "sertanejo": ['sertanejo'],
    "ska": ['ska'],
    "tango": ['tango']
}